Added --run switch for custom scripts.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -14,6 +14,8 @@
 #     --command   Show the docker run command to run the container
 #     --name N    Name the container 'N'
 #     --no-halt   Don't halt the container when the build finishes
+#     --run S     Copy script S into the container and run it from
+#                   the build area instead of the default 'make'.
 #END-HELP
 #
 
@@ -64,6 +66,11 @@ do
 	    NO_HALT="--env BUILD_NO_HALT=1"
 	    ;;
 
+	--run)
+	    RUN_ARG=$1
+	    shift
+	    ;;
+
 	--*)
 	    die "Unknown option ${OPTION}."
 	    ;;
@@ -72,6 +79,9 @@ done
 
 [ "$#" -eq 2 ] \
     || self_help 1
+
+[ -z "${RUN_ARG}" -o -f "${RUN_ARG}" ] \
+    || die "Can't find script '${RUN_ARG}'"
 
 
 # Build directory
@@ -82,6 +92,21 @@ BUILD_DIR="$1"
 echo "${BUILD_DIR}" | fgrep -q ':' \
     && die "Build directory cannot contain colons."
 BUILD_DIR=$(cd "${BUILD_DIR}" && pwd)
+
+
+# Run script, stored in the DOSB-specific area
+
+if [ -s "${RUN_ARG}" ]
+then
+    PRODUCTS="${BUILD_DIR}/DOSB"
+    rm -rf "${PRODUCTS}"
+    mkdir -p "${PRODUCTS}"
+
+    BUILD_RUN="${PRODUCTS}/build-script"
+
+    cp "${RUN_ARG}" "${BUILD_RUN}"
+    chmod +x "${BUILD_RUN}"
+fi
 
 
 # Container name
